storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@selfpentest/*':
    access: $all
    publish: $all
  '**':
    access: $all
    proxy: npmjs
log:
  - {type: stdout, format: pretty, level: http}
