storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@selfpentest/*':
    access: $all
    publish: $authenticated
  '**':
    access: $all
    proxy: npmjs
log:
  - {type: stdout, format: pretty, level: http}
